  
<div class="transf margem container">  
    <h2><center>Cadastrar Pessoa:</center></h2>
    <form action="cadastro.php" method="POST">
        <div class="form-row transf margem">
            <div class="form-group col-md-12">
                <label>Nome:</label>
                <input type="text" name="nome" class="form-control" id="nome">
            </div>
        </div>
        <div class="form-row transf margem">
            <div class="form-group col-md-6">
                <label>Selecione seu estado</label>